name: CI

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Upload file to SourceForge
        run: |
          dd if=/dev/zero of=myfile bs=1M count=10
          mkdir -p ~/.ssh/
          echo "${{ secrets.SOURCEFORGE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          rsync -r myfile pedroz@frs.sourceforge.net:/home/frs/project/pedroz/
        env:
          SOURCEFORGE_PRIVATE_KEY: ${{ secrets.SOURCEFORGE_PRIVATE_KEY }}


